name: goexample
stages:
- name: clone
  steps:
  - sourceCodeConfig:
      branch: master
      branchCondition: only
      url: https://github.com/zionwu/goexample.git
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      isShell: true
      shellScript: |-
        mkdir -p /go/src/github.com/zionwu
        ln -s `pwd` /go/src/github.com/zionwu/goexample
        cd /go/src/github.com/zionwu/goexample
        go test
- name: publish
  steps:
  - publishImageConfig:
      buildContext: .
      dockerfilePath: ./Dockerfile
      tag: docker-local/goexample:dev_${CICD_GIT_COMMIT}
